---
title: "Projet Market"
format: html
editor: visual
---

# Groupe:

**Ang Mingwei et Rousselin Quentin**

========================================

**Partie stat. globale**

**Library et import des données**

```{r}
library(ggplot2)
library(dplyr)
library(rAmCharts)

fp <- "data/table_client.csv"
df_client <- read.csv(fp)

fp <- "data/table_vehicule.csv"
df_vehic <- read.csv(fp)

fp <- "data/table_commande_reprise.csv"
df_cmd_reprise <- read.csv(fp)

fp <- "data/table_financement.csv"
df_financt <- read.csv(fp)
```

Preparation des données

```{r}

df_cmd_reprise$DATE_PANIER <- as.Date(df_cmd_reprise$DATE_PANIER)

```

**Analyse des clients**

```{r}
# Nombre de clients
N <- nrow(df_client) # Total
N
table(df_client$GENDER) #Homme/Femme
year <- 2026
df_client$AGE <- (year - df_client$YEAR_NAISSANCE)

# En fonction de l'âge
ggplot(df_client) + aes(AGE, fill=GENDER) + geom_histogram()

```

**Analyse des véhicules**

```{r}
nrow(df_vehic) # Nb total de véhicules

table(df_vehic$VEHICULE_TYPE)
# table(vehicules$VEHICULE_ENERGIE)
# table(vehicules$VEHICULE_CATEGORIE)

ggplot(df_vehic) + aes(VEHICULE_CATEGORIE, fill=VEHICULE_ENERGIE) + geom_bar()

# Nb véhicules par marque
count(df_vehic, VEHICULE_MARQUE, sort = TRUE)

# Nb véhicules par modele
count(df_vehic, VEHICULE_MODELE, sort = TRUE)
```

**Transactions**

```{r}
table(df_cmd_reprise$TYPE_PANIER)

summary(df_cmd_reprise$DATE_PANIER)
```

Marques et Modeles

```{r}
# Les marques de voitures qui ont le plus de commandes
by <- join_by(VEHICULE_ID)
df_vehic_cmd_repr <- left_join(df_vehic, df_cmd_reprise, by)

l <- count(df_vehic_cmd_repr, VEHICULE_MARQUE, sort = TRUE)$VEHICULE_MARQUE
l <- l[1:5]
l

df_vehic_cmd_repr <- df_vehic_cmd_repr[df_vehic_cmd_repr$VEHICULE_MARQUE %in% l,]

ggplot(df_vehic_cmd_repr) + aes(VEHICULE_MARQUE, fill=TYPE_LIVRAISON_COM) + geom_bar()
ggplot(df_vehic_cmd_repr) + aes(VEHICULE_MARQUE, PRIX_VENTE_TTC_COM) + geom_boxplot()

# Les modeles de voitures qui ont le plus de commandes

l <- count(df_vehic_cmd_repr, VEHICULE_MODELE, sort = TRUE)$VEHICULE_MODELE
l <- l[1:5]
l

df_vehic_cmd_repr <- df_vehic_cmd_repr[df_vehic_cmd_repr$VEHICULE_MODELE %in% l,]

ggplot(df_vehic_cmd_repr) + aes(VEHICULE_MODELE, fill=TYPE_LIVRAISON_COM) + geom_bar()
ggplot(df_vehic_cmd_repr) + aes(VEHICULE_MODELE, PRIX_VENTE_TTC_COM) + geom_boxplot()

```

**Mon hypothèse:**

Les français achètent-ils moins de voiture en générale (ou depuis le Covid/2019)?

Pour prouver: Analyse du marché automobile avant et après 2019
